---
- name: configuracion
  hosts: all
  user: root
  tasks:
    - name: "borrar index.html original"
      file:
        path: /var/www/html/index.html
        state: absent

    - name: "enviar el index correcto"
      synchronize: 
       src: index.html 
       dest: /var/www/html/
       
        
