---
- name: config
  hosts: all
  user: root
  tasks:
    - name: "enviar el .key"
      synchronize:
       src: apache-selfsigned.key
       dest: /etc/ssl/private/

    - name: "enviar .crt"
      synchronize:
       src: apache-selfsigned.crt
       dest: /etc/ssl/certs/
